language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.8
matrix:
  include:
    - python: 2.7
      script: tox -e lint
    - python: 3.7
      dist: xenial
install:
  - pip install tox-travis
script:
  - tox
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always
branches:
  only:
  - master
